### ISSUE TITLE
Cover image load issue

### ISSUE THREAD

**Issue by ZochoK** [Ressetkk/Iku-chan#1]
When I try get an information of 297974, bot tries to get a cover from https://t.nhentai.net/galleries/1553654/cover.jpg
This address returns a 404 error because the cover of this comic have a .png extension.
As the result bot doesn't show any picture in the message on discord. The rest of the information are displayed correctly

**Comment by Ressetkk** [comment]
Resolved in https://github.com/Ressetkk/Iku-chan/commit/7f93e8a4ade5e66240add2a9905889fe19af4b0f
